project:
  type: website
  output-dir: docs

website:
  title: "Mooda"
  repo-url: https://github.com/sequentialrant/myweb
  open-graph: true
  site-url: https://mooda.blog
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Blog
      - text: "Resources"
        file: static/resources/resources.qmd
      - text: About
        file: about.qmd
      - icon: github
        href: https://github.com/sequentialrant
      - icon: twitter
        href: https://twitter.com/sequentialrant

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



